language: python
python: "3.8"
dist: xenial

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install
  - pre-commit install-hooks

script:
  - pre-commit run --all-files
  - coverage run -m pytest aoc
